const _ = require("lodash");
const provisioningTemplateSample = {
    "id": 1818,
    "name": "Default Provisioning Config",
    "siteId": "635b908f5771a601e573ce73",
    "advancedAnalyticsIotLocationServerProfileName": "Default Advanced Analytics",
    "advancedAnalyticsSwitch": true,
    "advertisingProtocolMode": "iBeacon",
    "advertisingSwitch": false,
    "apuiPassword": "*",
    "apuiSwitch": false,
    "bleLbsIotLocationServerProfileName": null,
    "calledStationId": null,
    "cirrusWifiRTLSSwitch": false,
    "dayLightSaveTime": false,
    "description": null,
    "eddyStoneURL": "",
    "emissionFrequency": 200,
    "eventConfigurationName": null,
    "externalPortalCertificate": null,
    "hostName": null,
    "igmpSnooping": false,
    "iotRadioMode": "Disable",
    "ipv6L3ForwardingSwitch": false,
    "isAPUIPasswordChanged": false,
    "isClientBeTrackingPasswordChanged": false,
    "isSSHRootPasswordChanged": false,
    "isSSHSupportPasswordChanged": false,
    "isSnmpPasswordChanged": false,
    "isTrapPasswordChanged": false,
    "localLdapCertificate": null,
    "localRadSecCertificate": "RadSecCert",
    "systemLogDataList": [{
        "sysLogId": 226366,
        "syslogServerIp": "143.209.0.2",
        "sysLogServerPort": 514,
        "sysLogTlsSwitch": true,
		"sysLogCertification": 'SyslogCert',
    }],
    "logLevelAPDebug": "LOG_NOTICE",
    "logLevelNetwork": "LOG_NOTICE",
    "logLevelSecurity": "LOG_NOTICE",
    "logLevelSystem": "LOG_NOTICE",
    "logLevelUser": "LOG_NOTICE",
    "logLevelWireless": "LOG_NOTICE",
    "logRemoteSwitch": true,
    "logUploadPeriod": 1,
    "nameSpace": "",
    "ntpServerList": [
        "pool.ntp.org"
    ],
    "ouiAllowList": [],
    "password": "*",
    "pmdSwitch": false,
    "profileType": "DEFAULT",
    "redirectProxyServerPort": 1024,
    "redirectServerHost": "portal.ovcirrus.com",
    "redirectServerIP": "19.27.1.109",
    "redirectServerIPv6": "",
    "remotePath": null,
    "rfProfileName": "Default RF Profile",
    "scanningInterval": 100,
    "scanningSwitch": false,
    "serverIP": null,
    "serverPort": 0,
    "serverType": "SFTP",
    "SmpCommunity": null,
    "SmpPassword": "*",
    "SmpStatus": false,
    "SmpUserName": null,
    "SmpVersion": null,
    "sshRootPassword": "*",
    "sshSupportPassword": "*",
    "sshSwitch": false,
    "syslogServerIp": null,
    "syslogServerPort": 0,
    "syslogSwitch": false,
    "tftpServer": null,
    "timeZone": "Asia/Bangkok (GMT+07:00)",
    "trapCommunity": null,
    "trapPassword": "*",
    "trapServer": null,
    "trapStatus": false,
    "trapUserName": null,
    "trapVersion": null,
    "txChannel": [
        1,
        2,
        4
    ],
    "txPower": 4,
    "uploadToServerSwitch": false,
    "userName": null,
    "virtualIPAddress": "192.0.2.0",
    "vlanId": null,
    "vpnServers": [],
    "webServiceCertificate": null,
    "wifiIotLocationServerProfileName": null,
    "supplicant8021x": true,
    "certificate8021x": "Cert8021X",
    "roamingDomain": "*",
    "isRoamingDomainChanged": false,
    "discoverAllDeviceSwitch": false
};

module.exports = {
	...provisioningTemplateSample
};
