module.exports = {
	id: 115628,
	name: "Provisioning001",
	siteId: "67cf9d1744b39e5882733f8d",
	advancedAnalyticsIotLocationServerProfileName: "Default Advanced Analytics",
	advancedAnalyticsSwitch: true,
	advertisingProtocolMode: "iBeacon",
	advertisingSwitch: true,
	apuiPassword: "*",
	apuiSwitch: true,
	bleLbsIotLocationServerProfileName: "BLE Location",
	calledStationId: "1",
	certificate8021x: "Built-in Certificate",
	cirrusWifiRTLSSwitch: false,
	dayLightSaveTime: false,
	description: "Testing1",
	discoverAllDeviceSwitch: true,
	eddyStoneURL: null,
	emissionFrequency: 10240,
	eventConfigurationName: "",
	externalPortalCertificate: null,
	hostName: null,
	igmpSnooping: true,
	iotRadioMode: "BLE",
	ipv6L3ForwardingSwitch: true,
	isAPUIPasswordChanged: false,
	isClientBeTrackingPasswordChanged: false,
	isRoamingDomainChanged: false,
	isSSHRootPasswordChanged: false,
	isSSHSupportPasswordChanged: false,
	isSnmpPasswordChanged: false,
	isTrapPasswordChanged: false,
	localLdapCertificate: null,
	localRadSecCertificate: null,
	logLevelAPDebug: "LOG_CRIT",
	logLevelNetwork: "LOG_CRIT",
	logLevelSecurity: "LOG_CRIT",
	logLevelSystem: "LOG_CRIT",
	logLevelUser: "LOG_CRIT",
	logLevelWireless: "LOG_CRIT",
	logRemoteSwitch: true,
	logUploadPeriod: 1,
	macSec: true,
	nameSpace: null,
	ntpServerList: ["pool.ntp.org"],
	ouiAllowList: ["AA:AA:AA"],
	password: "*",
	pmdSwitch: true,
	profileType: "NORMAL",
	redirectProxyServerPort: 1024,
	redirectServerHost: "dev.portal.ovcirrus.com",
	redirectServerIP: "172.16.90.109",
	redirectServerIPv6: "",
	remotePath: "remotepath",
	rfProfileName: "Default RF Profile",
	roamingDomain: "*",
	scanningInterval: 100,
	scanningSwitch: true,
	serverIP: "1.1.1.1",
	serverPort: 22,
	serverType: "SFTP",
	snmpCommunity: "",
	snmpPassword: "*",
	snmpStatus: true,
	snmpUserName: "user",
	snmpVersion: "SNMPv3",
	sshRootPassword: "*",
	sshSupportPassword: "*",
	sshSwitch: true,
	supplicant8021x: true,
	syslogServerIp: "1.1.1.1",
	syslogServerPort: 514,
	syslogSwitch: true,
	systemLogDataList: [
		{
			sysLogId: 115627,
			sysLogServerPort: 514,
			sysLogTlsSwitch: false,
			syslogServerIp: "143.209.0.2"
		}
	],
	tftpServer: "1.1.1.1",
	timeZone: "Africa/Abidjan (GMT+00:00)",
	trapCommunity: "",
	trapPassword: "*",
	trapServer: "1.1.1.1",
	trapStatus: true,
	trapUserName: "user",
	trapVersion: "SNMPv3",
	txChannel: [1, 2, 4],
	txPower: 1,
	uploadToServerSwitch: true,
	userName: "user",
	virtualIPAddress: "192.0.2.0",
	vlanId: "2",
	vpnServers: ["VPNSetting001"],
	webServiceCertificate: null,
	wifiIotLocationServerProfileName: "Aeroscout Location",
	site: "67cf9d1744b39e5882733f8d"
};
